### PR TITLE
Add pom for building a jar file

### PR DESCRIPTION
**Pull request by harlow**
* This will allow users to run `mvn package` to build a jar file. The jar can then be added as an application dependency instead of copying all the connector source into a project.

### CODE REVIEW

**Comment by manango** [comment]
amazon-kinesis-connectors 1.1.2 is available in maven now:
http://search.maven.org/#artifactdetails%7Ccom.amazonaws%7Camazon-kinesis-connectors%7C1.1.2%7Cjar
pom.xml file is also available in the git repository.

**Comment by pkallos** [comment]
:tada: !!

**Comment by pkallos** [comment]
@alexanderdean FYI this might affect you

**Comment by alexanderdean** [comment]
Cheers @pkallos - yep we are very pleased about the Mavenization of all this!

**Pull request closed without merging**
